"""Pure release and runtime limits shared by the app and release controller."""

APPROVED_OPENAI_MODEL = "gpt-5.4-nano-2026-03-17"
APPROVED_AI_DAILY_ATTEMPT_LIMIT = 120
APPROVED_AI_MONTHLY_TOKEN_LIMIT = 150_000
APPROVED_AI_SESSION_ATTEMPT_LIMIT_PER_MINUTE = 3
APPROVED_AI_GLOBAL_ATTEMPT_LIMIT_PER_MINUTE = 20
APPROVED_AI_MAX_CONCURRENT_TURNS = 15
APPROVED_CHAT_OUTPUT_TOKEN_LIMIT = 2_800
PLANNING_TOKEN_RESERVATION = 16_000
ANSWERING_TOKEN_RESERVATION = 80_000
